name: admaya
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  country_code_picker: 
    git:
      url: https://github.com/veekeo/CountryCodePicker

  modal_bottom_sheet: ^2.0.1
  collection: ^1.15.0
  universal_platform: ^1.0.0+1
  delayed_display: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  carousel_nullsafety: ^0.1.1
  flutter_rating_bar: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1

flutter_native_splash: 
  color: "#ff4876"
  image: assets/images/splash_logo.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/google.png
    - assets/images/envelope.png
    - assets/images/location.png
    - assets/images/hairdresser.jpg


  
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf

